# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [117]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [118]:
# a =
a=pd.Series([100,200,300,400])

Print a, and data type

In [119]:
print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [120]:
print(a[2:3])

2    300
dtype: int64

What are the values of index for series a?

In [121]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [122]:
a.index=['c','a','b','d']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [123]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [124]:
a=a.sort_index()
print(a)

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [125]:
# b =
b=pd.Series(['e','f','g',800,450,100])
print(b)

0      e
1      f
2      g
3    800
4    450
5    100
dtype: object

Append b series at the end of a series

In [126]:
# a =
a=pd.concat([a,b])
print(a)

a    200
b    300
c    100
d    400
0      e
1      f
2      g
3    800
4    450
5    100
dtype: object

In [127]:
#print a again after appending b into it
print(a)

a    200
b    300
c    100
d    400
0      e
1      f
2      g
3    800
4    450
5    100
dtype: object

Sort the values in descending order of a and print the index of the sorted series

In [128]:
# a =

a_sorted = a[pd.to_numeric(a, errors='coerce').notna()].astype(int).sort_values(ascending=False)

print(a_sorted.index)

Index([3, 4, 'd', 'b', 'a', 'c', 5], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [129]:
# df =
df=pd.DataFrame(a)
print(df)

     0
a  200
b  300
c  100
d  400
0    e
1    f
2    g
3  800
4  450
5  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [130]:
print(df.shape)

(10, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [131]:
# yep its same as the series.
print(df.index)

Index(['a', 'b', 'c', 'd', 0, 1, 2, 3, 4, 5], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [132]:
print(df.head())

     0
a  200
b  300
c  100
d  400
0    e

In [133]:
print(df.tail())

     0
1    f
2    g
3  800
4  450
5  100

Rename the column of the dataframe as 'points'

In [134]:
df.columns=['points']
print(df)

  points
a    200
b    300
c    100
d    400
0      e
1      f
2      g
3    800
4    450
5    100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [135]:
#Create fruits array

# fruits =
fruits_array=np.array(np.random.choice(['orange','mango','apple'],size=7))
print(fruits_array)

['mango' 'apple' 'apple' 'mango' 'orange' 'mango' 'orange']

In [136]:
#Create series fruits out of fruits array

# fruits =
fruits = pd.Series(fruits_array)

print(fruits)

0     mango
1     apple
2     apple
3     mango
4    orange
5     mango
6    orange
dtype: object

Change the index of fruits to the index of dataframe df

In [137]:
fruits.index = df.index[:7]

print(fruits)

a     mango
b     apple
c     apple
d     mango
0    orange
1     mango
2    orange
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [138]:
df['fruits'] = fruits

print(df.head())

  points  fruits
a    200   mango
b    300   apple
c    100   apple
d    400   mango
0      e  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [139]:
# d1 =

d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})

Print(d1)

In [140]:

print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [141]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [142]:
city = d1['city']

print(city)

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object

print city <br>
What is the type of city.

In [143]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [144]:
# d2 =
d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})

print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [145]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [146]:
# d3 =
d3 = pd.concat([d1, d2])

print(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [147]:
lesstemp=d3[d3['Temperature']<=20]
print(lesstemp)
print(len(lesstemp))

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2
3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [148]:
greattemp=d3[d3['Temperature']>=35]
print(greattemp)

          city  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [149]:
# write function here

# def is_ut(x):

#     # write code below

# d3['is_ut'] =
# write function here

def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)

In [150]:
# print d3
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [151]:
# write function here
def c_to_f(temp):
    return (temp * 9/5) + 32
d3['Temperature_F'] = d3['Temperature'].apply(c_to_f)

In [152]:
# check function c_to_f(10)
# check function
print(c_to_f(10))

50.0

In [153]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
print(d3)

          city  Temperature  is_ut  Temperature_F  temp_farenhiet
0   Chandigarh           15   True           59.0            59.0
1        Delhi           22   True           71.6            71.6
2       Kanpur           20  False           68.0            68.0
3      Chennai           26  False           78.8            78.8
4       Manali           -2  False           28.4            28.4
0    Bengalaru           24  False           75.2            75.2
1   Coimbatore           35  False           95.0            95.0
2    Srirangam           36  False           96.8            96.8
3  Pondicherry           39   True          102.2           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d3 such that it contains the cities which are union territories.

In [154]:
d1_ut = d3[d3['is_ut'] == True]
print(d1_ut)

          city  Temperature  is_ut  Temperature_F  temp_farenhiet
0   Chandigarh           15   True           59.0            59.0
1        Delhi           22   True           71.6            71.6
3  Pondicherry           39   True          102.2           102.2

Select a subset of the dataframe d3 such that it contains the cities which only have temperature above 90 Farenhiet.

In [155]:

d3_hot = d3[d3['temp_farenhiet'] > 90]
print(d3_hot)

          city  Temperature  is_ut  Temperature_F  temp_farenhiet
1   Coimbatore           35  False           95.0            95.0
2    Srirangam           36  False           96.8            96.8
3  Pondicherry           39   True          102.2           102.2

Select only the first three rows of the dataframe d1.

In [156]:
d1_first3 = d1.head(3)
print(d1_first3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [157]:
d3.iloc[:, -2:]

   Temperature_F  temp_farenhiet
0           59.0            59.0
1           71.6            71.6
2           68.0            68.0
3           78.8            78.8
4           28.4            28.4
0           75.2            75.2
1           95.0            95.0
2           96.8            96.8
3          102.2           102.2

## Groupby

In [158]:
# Create a dataframe using dictionary of your choice

# data =
# Create a dataframe using dictionary of your choice

import pandas as pd

data = {
    'Name': ['Raunak','Rivanshi', 'Bob', 'Charlie'],
    'Age': [21,23, 30, 22],
    'City':['Delhi','Delhi', 'Mumbai', 'Chennai'],
    'Gender':['Female','Female','Male','Male']
}

df = pd.DataFrame(data)

print(df)

       Name  Age     City  Gender
0    Raunak   21    Delhi  Female
1  Rivanshi   23    Delhi  Female
2       Bob   30   Mumbai    Male
3   Charlie   22  Chennai    Male

In [159]:
# Use Groupby of single column with aggregate sum()
df.groupby('Gender')['Age'].sum()

Gender
Female    44
Male      52
Name: Age, dtype: int64

In [160]:
# Use Groupby of single column with aggregate count()
df.groupby('Gender')['Name'].count()

Gender
Female    2
Male      2
Name: Name, dtype: int64

In [161]:
# Use Groupby of single column with aggregate min() and max()
result = df.groupby('Gender')['Age'].agg(['min', 'max'])

print(result)

        min  max
Gender
Female   21   23
Male     22   30

In [162]:
# Use Groupby of any 2 columns with aggregate mean()
df.groupby(['City', 'Gender'])['Age'].mean().reset_index()

      City  Gender   Age
0  Chennai    Male  22.0
1    Delhi  Female  22.0
2   Mumbai    Male  30.0

In [163]:
# Use Groupby of any 2 columns with aggregate min() and max()
df.groupby(['City', 'Gender'])['Age'].agg(['min', 'max']).reset_index()

      City  Gender  min  max
0  Chennai    Male   22   22
1    Delhi  Female   21   23
2   Mumbai    Male   30   30

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [164]:
# a =
import pandas as pd

a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [165]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [166]:
len(a)

457

What is the type of a?

In [167]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>